using UnityEngine;
using UnityEngine.UI;

public class KK_UIManager : MonoBehaviour
{
    public static KK_UIManager Instance;

    [Header("â¤ï¸ ëª©ìˆ¨ UI")]
    public Text lifeText;
    [Header("ğŸ”« íŒŒì›Œ UI")]
    public Text powerText;
    public Image screenUI;
    public Text clearText;
    private void Awake()
    {
        if (Instance == null) Instance = this;
        else Destroy(gameObject);
    }
    public void Start()
    {
        screenUI.color = new Color (0, 0, 0, 0f);
        clearText.color = new Color (0, 0, 0, 0);               
    }

    public void Update()
    {
        if(KK_Boss.instance.isDead == true)
        {
            screenUI.color = new Color (0, 0, 0, 0.5f);
            clearText.color = new Color (1, 1, 1, 1);
        }
    }

    public void UpdatePowerUI(int power)
    {
        powerText.text = $"{power} lv";
        // íŒŒì›Œ ì•„ì´ì½˜ êµì²´í•˜ë ¤ë©´ ì—¬ê¸°ì— ì¶”ê°€
    }

    public void UpdateLifeUI(int life)
    {
        lifeText.text = $"x {life}";
        // ë¼ì´í”„ ì•„ì´ì½˜ êµì²´í•˜ë ¤ë©´ ì—¬ê¸°ì— ì¶”ê°€
    }
}
